// Generated by https://pagedraw.io/pages/4775
import React from 'react';
import './bottombar.css';

function render() {
    return <div className="bottombar">
        <div className="bottombar-0">
            <div className="bottombar-bottombar-8">
                <div className="bottombar-0-0-0">
                    <div className="bottombar-0-0-0-0" /> 
                    <img src="https://ucarecdn.com/b4b7772e-de03-478a-82b4-5580cee1c380/" className="bottombar-image-1" /> 
                    <div className="bottombar-0-0-0-2" /> 
                </div>
                <div className="bottombar-0-0-1">
                    <div className="bottombar-website_-_taciana_pereira_amp_pagedraw_-8">
                        Website - Taciana Pereira &amp;amp; Pagedraw
                    </div>
                </div>
                <div className="bottombar-0-0-2">
                    <div className="bottombar-contato_rugbyxchange_com_br_-5">
                        contato@rugbyxchange.com.br
                    </div>
                </div>
                <div className="bottombar-0-0-3">
                    <div className="bottombar-2">2017</div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}