// Generated by https://pagedraw.io/pages/4775
import Topbar from './topbar';
import Profile from './profile';
import Bottombar from './bottombar';
import React from 'react';
import './main.css';

function render() {
    return <div className="main">
        <div className="main-0">
            <div className="main-main-9">
                <div className="main-0-0-0">
                    <div className="main-topbar-9"><Topbar /> </div>
                </div>
                <div className="main-0-0-1">
                    <div id={'mission'} className="main-image-3">
                        <div className="main-0-0-1-0-0">
                            <div className="main-0-0-1-0-0-0" /> 
                            <div className="main-bem_vindx_ao_rugbyxchange_-2">
                                Bem Vindx ao rugbyXchange!
                            </div>
                            <div className="main-0-0-1-0-0-2" /> 
                        </div>
                    </div>
                </div>
                <div className="main-0-0-2">
                    <div className="main-0-0-2-0" /> 
                    <div className="main-rectangle_2">
                        <div className="main-0-0-2-1-0">
                            <div className="main-0-0-2-1-0-0" /> 
                            <div className="main-miss_o_-2">Missão</div>
                            <div className="main-0-0-2-1-0-2" /> 
                        </div>
                    </div>
                    <div className="main-0-0-2-2" /> 
                </div>
                <div className="main-0-0-3">
                    <div className="main-nossa_miss_o_mentorar_e_auxiliar_na_educa_o_de_jogadoras_de_rugby_que_est_o_no_ensino_fundamental_para_que_consigam_bolsas-atleta_nas_melhores_universidades_dos_estados_unidos_nbsp_queremos_ensinar_a_mulheres_jovens_que_o_rugby_pode_ser_um_meio_para_alcan_ar_diversos_objetivos_inclusive_os_relacionados_nbsp_educa_o_nbsp_-0">
                        Nossa missão é mentorar e auxiliar na educação de jogadoras de rugby que estão no ensino fundamental para que consigam bolsas-atleta nas melhores universidades dos Estados Unidos.&amp;nbsp;Queremos ensinar a mulheres jovens que o rugby pode ser um meio para alcançar diversos objetivos, inclusive os relacionados à&amp;nbsp;educação.&amp;nbsp;
                    </div>
                </div>
                <div className="main-0-0-4">
                    <div id={'who'} className="main-image-9" /> 
                </div>
                <div className="main-0-0-5">
                    <div className="main-0-0-5-0" /> 
                    <div className="main-rectangle_3">
                        <div className="main-0-0-5-1-0">
                            <div className="main-quem_somos_-5">Quem Somos</div>
                        </div>
                    </div>
                    <div className="main-0-0-5-2" /> 
                </div>
                <div className="main-0-0-6">
                    <div className="main-0-0-6-0" /> 
                    <div className="main-rectangle_8">
                        <div className="main-0-0-6-1-0">
                            <div className="main-profile-4">
                                <Profile bio={"Taciana já praticou futebol, basquete, vôlei, triathlon, muay-thai e jiu-jitsu, mas se apaixonou quando começou a jogar rugby no fim do seu primeiro ano de Bioengenharia na Universidade de Harvard. Lá ela teve contato com atletas recrutados para diversas modalidades em universidades nos EUA. Hoje trabalha com engenharia de tecidos, mas acredita no poder do esporte para transformar vidas e dar acesso à educação."} name={"Taciana Pereira"} image_url={"https://ucarecdn.com/19976a93-1c48-40d9-b099-b2d8a5786dee/"} /> 
                            </div>
                            <div className="main-profile-3">
                                <Profile bio={"Ana começou a jogar rugby aos 22 anos, pelo Urutau (Curitiba/PR). Desde então não conseguiu mais largar o esporte por seus valores cativantes e se envolveu em diversas atividades extra-campo, tendo sido Diretora e Presidente do clube. Advogada formada e pós-graduada pela PUC-PR, acredita que o esporte é uma ferramente chave para o empoderamento feminino."} name={"Ana Cassia Sato"} image_url={"https://ucarecdn.com/35833982-69ec-486b-a556-7023c6861277/"} /> 
                            </div>
                        </div>
                        <div className="main-0-0-6-1-1">
                            <div className="main-profile-2">
                                <Profile bio={"Isadora passou anos jogando futebol até conhecer o rugby no seu segundo ano de faculdade. Filha de pais brasileiros, mudou-se em 2014 para o Brasil para perseguir o sonho de ser atleta olímpica de rugby Sevens nos Jogos Olímpicos Rio2016. Hoje, faz parte da liderança da seleção brasileira e usa sua visibilidade para ser a transformação que deseja ver no mundo. Graduada em Biologia e Direitos Humanos pela Universidade de Columbia, tem um olhar crítico e consciente quanto à relevância do esporte como ferramenta de transformação."} name={"Isadora Cerullo"} image_url={"https://ucarecdn.com/c65cc8ae-17d6-4f7d-abe1-db65a6485508/"} /> 
                            </div>
                            <div className="main-profile-5">
                                <Profile bio={"Taciana já praticou futebol, basquete, vôlei, triathlon, muay-thai e jiu-jitsu, mas se apaixonou quando começou a jogar rugby no fim do seu primeiro ano de Bioengenharia na Universidade de Harvard. Lá ela teve contato com atletas recrutados para diversas modalidades em universidades nos EUA. Hoje trabalha com engenharia de tecidos, mas acredita no poder do esporte para transformar vidas e dar acesso à educação."} name={"Marjorie Yu Enia"} image_url={"https://ucarecdn.com/19976a93-1c48-40d9-b099-b2d8a5786dee/"} /> 
                            </div>
                        </div>
                    </div>
                    <div className="main-0-0-6-2" /> 
                </div>
                <div className="main-0-0-7">
                    <div id={'participate'} className="main-image-4" /> 
                </div>
                <div className="main-0-0-8">
                    <div className="main-0-0-8-0" /> 
                    <div className="main-rectangle_4">
                        <div className="main-0-0-8-1-0">
                            <div className="main-0-0-8-1-0-0" /> 
                            <div className="main-participe_-3">Participe</div>
                            <div className="main-0-0-8-1-0-2" /> 
                        </div>
                    </div>
                    <div className="main-0-0-8-2" /> 
                </div>
                <div className="main-0-0-9">
                    <div className="main-para_participar_primeiro_certifique-se_de_que_voc_se_encaixa_nos_requisitos_do_programa_1">
                        <div>Para participar, primeiro certifique-se de que você se encaixa nos requisitos do programa:</div>
                        <br/>
                        <div>1. Você está no 8o ou 9o ano do ensino fundamental em uma escola do ensino público, ou tem 100% de bolsa em uma escola particular;</div>
                        <br/>
                        <div>2. Você joga rugby;</div>
                        <div>3. Você tem um desempenho escolar com média acima de 8;</div>
                        <br/>
                        <div>4. Você é motivada e está disposta a trabalhar muito para conseguir o que quer.</div>
                        <br/>
                        <div>Obs.: Não é necessário falar inglês para participar do programa.</div>
                        <br/>
                        <div>Se você se enquadra nesses pré-requisitos, preencha este formulário e envie os seguintes documentos para o email contato@rugbyxchange.com.br (assunto &quot;Seu Nome Completo - Inscrição&quot;):</div>
                        <br/>
                        <div>1. Carta de recomendação de umx treinadorx, preferencialmente falando sobre sua atitude e desempenho no esporte;</div>
                        <br/>
                        <div>2. Carta de recomendação de umx profressorx, preferencialmente falando sobre seu desempenho acadêmico;</div>
                        <br/>
                        <div>3. Histórico escolar a partir do 7o ano.</div>
                        <br/>
                        <div>As fases de seleção são as seguintes:</div>
                    </div>
                </div>
                <div className="main-0-0-10">
                    <div className="main-0-0-10-0" /> 
                    <div className="main-rectangle_7">
                        <div className="main-0-0-10-1-0">
                            <div className="main-07">
                                07/08/2017 - 15/09/2017: Período de inscrições25/09: Anúncio das aprovadas para a segunda fase26/09 - 13/10: Período de entrevista das finalistas20/10: Anúncio das escolhidas para o rugbyXchange
                            </div>
                        </div>
                    </div>
                    <div className="main-0-0-10-2" /> 
                </div>
                <div className="main-0-0-11">
                    <div className="main-0-0-11-0" /> 
                    <div className="main-para_quaisquer_d_vidas_sobre_o_processo_ou_problemas_com_a_inscri_o_favor_enviar_um_email_para_contato_rugbyxchange_com_br_nbsp_-7">
                        Para quaisquer dúvidas sobre o processo ou problemas com a inscrição, favor enviar um email para contato@rugbyxchange.com.br.&amp;nbsp;
                    </div>
                    <div className="main-0-0-11-2" /> 
                </div>
                <div className="main-0-0-12">
                    <img src="https://ucarecdn.com/59d1a840-2ccd-4de3-a3e9-ecc0744cbcf2/" id={'supporters'} className="main-image-5" /> 
                </div>
                <div className="main-0-0-13">
                    <div className="main-0-0-13-0" /> 
                    <div className="main-rectangle_5">
                        <div className="main-0-0-13-1-0">
                            <div className="main-0-0-13-1-0-0" /> 
                            <div className="main-nosso_apoio_-8">Nosso Apoio</div>
                            <div className="main-0-0-13-1-0-2" /> 
                        </div>
                    </div>
                    <div className="main-0-0-13-2" /> 
                </div>
                <div className="main-0-0-14">
                    <div className="main-0-0-14-0" /> 
                    <div className="main-divulgaremos_nossas_parcerias_em_breve_para_nos_apoiar_mande_um_email_para_apoio_rugbyxchange_com_br_-6">
                        Divulgaremos nossas parcerias em breve!Para nos apoiar, mande um email para apoio@rugbyxchange.com.br
                    </div>
                    <div className="main-0-0-14-2" /> 
                </div>
                <div className="main-0-0-15">
                    <img src="https://ucarecdn.com/14a19e14-9a66-4a04-8669-6e9a33d257af/" id={'contact'} className="main-image-40" /> 
                </div>
                <div className="main-0-0-16">
                    <div className="main-0-0-16-0" /> 
                    <div className="main-rectangle_6">
                        <div className="main-0-0-16-1-0">
                            <div className="main-0-0-16-1-0-0" /> 
                            <div className="main-contato_-5">Contato</div>
                            <div className="main-0-0-16-1-0-2" /> 
                        </div>
                    </div>
                    <div className="main-0-0-16-2" /> 
                </div>
                <div className="main-0-0-17">
                    <div className="main-0-0-17-0" /> 
                    <div className="main-se_voc_tem_alguma_d_vida_sugest_o_ou_acha_que_deve_ser_considerada_mesmo_n_o_estando_dentro_dos_pr_-requisitos_mande_um_email_para_contato_rugbyxchange_com_br_-4">
                        Se você tem alguma dúvida, sugestão ou acha que deve ser considerada mesmo não estando dentro dos pré-requisitos, mande um email para contato@rugbyxchange.com.br
                    </div>
                    <div className="main-0-0-17-2" /> 
                </div>
                <div className="main-0-0-18" /> 
                <div className="main-0-0-19">
                    <div className="main-bottombar-1">
                        <Bottombar color={"grey"} /> 
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}