// Generated by https://pagedraw.io/pages/4775
import React from 'react';
import './profile.css';

function render() {
    return <div className="profile">
        <div className="profile-0">
            <div className="profile-profile-7">
                <div className="profile-0-0-0">
                    <img src={this.props.image_url} className="profile-image-9" /> 
                </div>
                <div className="profile-0-0-1">
                    <div className="profile-taciana_pereira_-4">
                        { this.props.name }
                    </div>
                </div>
                <div className="profile-0-0-2">
                    <div className="profile-taciana_j_praticou_futebol_basquete_v_lei_triathlon_muay-thai_e_jiu-jitsu_mas_se_apaixonou_quando_come_ou_a_jogar_rugby_no_fim_do_seu_primeiro_ano_de_bioengenharia_na_universidade_de_harvard_l_ela_teve_contato_com_atletas_recrutados_para_diversas_modalidades_em_universidades_nos_eua_hoje_trabalha_com_engenharia_de_tecidos_mas_acredita_no_poder_do_esporte_para_transformar_vidas_e_dar_acesso_educa_o_-6">
                        { this.props.bio }
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}