// Generated by https://pagedraw.io/pages/4775
import React from 'react';
import './topbar.css';

function render() {
    return <div className="topbar">
        <div className="topbar-0">
            <div className="topbar-topbar-4">
                <div className="topbar-0-0-0">
                    <div className="topbar-image-9">
                        <div className="topbar-0-0-0-0-0">
                            <img src="https://ucarecdn.com/b4b7772e-de03-478a-82b4-5580cee1c380/" className="topbar-image-4" /> 
                        </div>
                    </div>
                </div>
                <div className="topbar-0-0-1">
                    <div className="topbar-rectangle-4">
                        <div className="topbar-0-0-1-0-0">
                            <div className="topbar-0-0-1-0-0-0" /> 
                            <a href="#mission" className="topbar-0-0-1-0-0-1">
                                <div className="topbar-miss_o_-5">Missão</div>
                            </a>
                            <div className="topbar-0-0-1-0-0-2" /> 
                            <a href="#who" className="topbar-0-0-1-0-0-3">
                                <div className="topbar-quem_somos_-8">Quem Somos</div>
                            </a>
                            <div className="topbar-0-0-1-0-0-4" /> 
                            <a href="#participate" className="topbar-0-0-1-0-0-5">
                                <div className="topbar-participe_-3">Participe</div>
                            </a>
                            <div className="topbar-0-0-1-0-0-6" /> 
                            <a href="#supporters" className="topbar-0-0-1-0-0-7">
                                <div className="topbar-nosso_apoio_-6">Nosso Apoio</div>
                            </a>
                            <div className="topbar-0-0-1-0-0-8" /> 
                            <a href="#contact" className="topbar-0-0-1-0-0-9">
                                <div className="topbar-contato_-7">Contato</div>
                            </a>
                            <div className="topbar-0-0-1-0-0-10" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}